#!/usr/bin/env bash
# script should display the contents of the current directory in list format.
#  script should only display the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
